FROM python:3.12-slim
WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

ENV DOCKER_CONTAINER=1

RUN useradd -m -u 1000 sentry_user
USER sentry_user

EXPOSE 8080

COPY . .

CMD ["python", "-m", "agent"]
